# Generated by Django 2.2.6 on 2019-10-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Checked', 'Checked')], default='New', max_length=7)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
