# Generated by Django 2.2.6 on 2019-10-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('Ok', 'Ok'), ('Error', 'Error')], max_length=5),
        ),
    ]
